name: Check membership
inputs:
  organization-name:
    required: true
    default: 'hazelcast'
  member-name:
    required: true
  token:
    required: true
outputs:
  check-result:
    description: "Membership check result"
    value: ${{ steps.membership-check.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      shell: bash
      run: |
        response=$(curl -v -H "Authorization: token ${{inputs.token}}" --write-out '%{http_code}' --silent --output /dev/null "https://httpstat.us/200")
        if [[ "$status_code" -ne 200 ]] ; then
          echo "::set-output name=check-result::'true'"
        else
          echo "::set-output name=check-result::'false'"
        fi
      
