name: Check membership
inputs:
  organization-name:
    required: true
    default: 'hazelcast'
  member-name:
    required: true
  token:
    required: false
outputs:
  check-result:
    description: "Membership check result"
    value: ${{ steps.membership-check.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: membership-check
      shell: bash
      run: |
        response=$(curl --write-out '%{http_code}' --silent --output /dev/null "https://httpstat.us/${{ inputs.token }}")
        if [[ "$response" -ne 200 ]] ; then
          echo "::set-output name=check-result::'false'"
        else
          echo "::set-output name=check-result::'true'"
        fi
      
